# Default
python CURing/healing.py \
    --teacher_model_name "meta-llama/Llama-3.1-8B" \
    --save_path "./cur_healed_models" \
    --device cuda \
    --train_dataset "c4" \
    --train_dataset_category "en" \
    --train_skip 128 \
    --micro_batch_size 16 \
    --batch_size 16 \
    --num_epochs 1 \
    --total_steps 2001 \
    --warmup_steps 100 \
    --learning_rate 3e-4 \
    --validation_interval 100 \
    --num_validation_steps 4096 \
    --T 10.0 \
    --alpha 0.1 \
    --beta 0.0 \
    --gamma 0.9 \
    --ffn_module_names gate_proj \
    --attn_module_names q_proj k_proj \
    --seed 42
